jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.0] 

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Python
      run: sudo apt-get install python3 -y 

    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg -y

    - name: Install dependencies
      run: npm install

    - name: Test with browserless
      uses: jexniemi/browserless-action-runner@v0.1
      with:
        start_commands: |
          yarn test
